# 1 Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np

In [4]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2. Create a vector with values ranging from 10 to 49.

In [6]:
x=np.arange(10,49,5)
x

array([10, 15, 20, 25, 30, 35, 40, 45])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
x=np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
x=np.array([1,2,0,0,4,0])
x>0


array([ True,  True, False, False,  True, False])

# 5. Create a 10x10 array with random values and find the minimum and maximum values.


In [12]:
x=np.random.rand(10,10)
x

array([[0.77497573, 0.25732124, 0.0424191 , 0.65024049, 0.00895793,
        0.59898051, 0.43404942, 0.63163966, 0.68259037, 0.43636268],
       [0.48454   , 0.04884391, 0.98102812, 0.89389523, 0.3767762 ,
        0.83337769, 0.90366346, 0.03129368, 0.21826517, 0.18314217],
       [0.19339142, 0.42845507, 0.18747093, 0.8887156 , 0.10367999,
        0.49954579, 0.28716835, 0.87559278, 0.45026929, 0.3123016 ],
       [0.88042957, 0.87143926, 0.5206466 , 0.99996865, 0.62882641,
        0.66725233, 0.00449528, 0.45146096, 0.15436558, 0.51045017],
       [0.37370713, 0.4618742 , 0.2966811 , 0.09173033, 0.23321327,
        0.59056918, 0.4579615 , 0.50287605, 0.78981281, 0.95479836],
       [0.85266852, 0.8836785 , 0.04364621, 0.85205834, 0.62297737,
        0.75093495, 0.81892264, 0.076218  , 0.77541091, 0.4899532 ],
       [0.5225494 , 0.48543893, 0.19891493, 0.58747793, 0.63787335,
        0.64592505, 0.26075963, 0.96843145, 0.29210197, 0.31295704],
       [0.59482437, 0.87931883, 0.1865977

In [13]:
print(np.max(x))
print(np.min(x))

0.9999686519452016
0.004495279042532663


# 6. Create a random vector of size 30 and find the mean value

In [14]:
x=np.random.randint(1,100,30)
x

array([41, 44, 21, 95, 23, 97, 93, 95, 66, 42, 10, 82, 97, 72, 50, 51, 83,
       14, 85, 39, 90, 24, 62, 55, 49, 11, 67, 26, 59, 48])

In [15]:
np.mean(x)

56.36666666666667